### ISSUE TITLE
range.hpp in VS2013

### ISSUE THREAD

**Issue by proomer** [harrism/hemi#17]
File range.hpp won't compile in VS2013 (CUDA 7.5). The problem seems to be line 228. The following errors are reported by VS:

Warning	1	warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\configure.h	34	1	HemiTest
Error	2	error C2144: syntax error : 'auto' should be preceded by ';'	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\range\range.hpp	228	1	HemiTest
Error	3	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\range\range.hpp	228	1	HemiTest
Error	4	error C2238: unexpected token(s) preceding ';'	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\range\range.hpp	228	1	HemiTest
Error	5	error C2143: syntax error : missing ';' before '<end Parse>'	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\range\range.hpp	228	1	HemiTest
Error	6	error C2988: unrecognizable template declaration/definition	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\range\range.hpp	228	1	HemiTest
Error	7	error C2059: syntax error : '<end Parse>'	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\range\range.hpp	228	1	HemiTest
Error	8	error C2238: unexpected token(s) preceding ';'	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\range\range.hpp	233	1	HemiTest
Error	9	error C2144: syntax error : 'bool' should be preceded by ';'	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\range\range.hpp	236	1	HemiTest
Error	10	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	c:\...\visual studio 2013\projects\hemitest\hemitest\hemi\range\range.hpp	236	1	HemiTest

**Comment by harrism** [comment]
The issue appears to be that VS2013 does not support C++11 `constexpr`. 
http://stackoverflow.com/questions/20264644/constexpr-not-compiling-in-vc2013

So you will need to upgrade your compiler. Either use VC2015 or install the November 2013 CTP as linked from the above StackOverflow answer. This is not a Hemi issue, so closing.

**Comment by taketwo** [comment]
Unfortunately CUDA does not support VS2015 as a host compiler, so we have to stick with VS2013. I had this problem recently, the following patch solves the problem for me:

```
diff --git a/hemi/range/range.hpp b/hemi/range/range.hpp
index 43411f4..6a5ebb2 100644
--- a/hemi/range/range.hpp
+++ b/hemi/range/range.hpp
@@ -46,7 +46,7 @@ struct range_iter_base : std::iterator<std::input_iterator_tag, T> {
 
     DEVICE_CALLABLE
     bool operator !=(range_iter_base const& other) const {
-        return not (*this == other);
+        return !(*this == other);
     }
 
 protected:
@@ -92,7 +92,7 @@ struct range_proxy {
 
             DEVICE_CALLABLE
             bool operator !=(iter const& other) const {
-                return not (*this == other);
+                return !(*this == other);
             }
 
         private:
@@ -222,18 +222,14 @@ infinite_range_proxy<T> range(T begin) {
 
 namespace traits {
 
-template <typename C>
+template <typename T>
 struct has_size {
-    template <typename T>
-    static constexpr auto check(T*) ->
-        typename std::is_integral<
-            decltype(std::declval<T const>().size())>::type;
-
-    template <typename>
-    static constexpr auto check(...) -> std::false_type;
-
-    using type = decltype(check<C>(0));
-    static constexpr bool value = type::value;
+    typedef char Yes;
+    typedef Yes No[2];
+    template <typename U, U> struct really_has;
+    template <typename C> static Yes& Test(really_has <size_t (C::*)() const, &C::size>*);
+    template <typename> static No& Test(...);
+    static bool const value = sizeof(Test<T>(0)) == sizeof(Yes);
 };
 
 } // namespace traits
```
